<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>2do reminder app</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
<div class="container">
    <h1>2do Complete</h1>
    <div>
        <h2>
            Remember Shit, Get Ripped
        </h2>
    </div>

    <?php
    if (isset($todos)) { ?>
    <form method="get" action="/delete" class="border border-dark">
        <?php foreach ($todos as $k => $todo) { ?>
            <div class="form-check">
                <input type="checkbox" name="todo" value="<?= htmlspecialchars($todo['id']) ?>" class="form-check-input"
                       id="materialChecked<?= $k ?>" aria-label="Checkbox for following text input">
                <label class="form-check-label"
                       for="materialChecked<?= $k ?>"><?= htmlspecialchars($todo['todo']) ?></label>
            </div>
        <?php }
        } else {
            echo 'Get some goals loser';
        };
        ?>
        <button type="submit" value="Delete Selected" class="btn btn-primary">Delete Selected</button>
    </form>
    <div class="pt-3">
        <a href="/">See what else you need to do.</a>
    </div>

</body>
</html>