<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>2do reminder app</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="/JS/main.js" defer></script>
</head>
<body>
<div class="container">
    <h1>2do</h1>
    <div>
        <h2>
            Remember Shit, Get Ripped
        </h2>
    </div>

<a href="/complete">See what you've done!</a>


</body>
</html>